language: node_js
node_js:
  - 10.16.3
cache: npm

before_install:
  - export PATH="$HOME/.yarn/bin:$PATH"

install: 
  - npm install

script:
  - npm test
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages


